@baseUrl = http://localhost:3000

### Delete film identified by 2
DELETE {{baseUrl}}/films/2

### Update the pizza identified by 2
PATCH {{baseUrl}}/films/2
Content-Type: application/json

{
    "duration":"1000"
}


