@baseUrl = http://localhost:3000

### get all film
GET {{baseUrl}}/films

### Delete film identified by 2
DELETE {{baseUrl}}/films/3

### Update the pizza identified by 2
PATCH {{baseUrl}}/films/4
Content-Type: application/json

{
    "duration":"100"
}


